---
title: "Welcome!"
---

This site contains the materials for the R/Pharma workshop titled, [Developing & Testing Your Shiny Application](https://www.eventbrite.com/e/developing-testing-your-shiny-application-tickets-728472048507).

## Workshop Description

This talk takes a deep dive into the world of testing shiny applications, covering strategies for determining what needs to be tested to ensure your app's functional accuracy and reliability. Shiny's reactive programming model requires specialized approaches to testing, distinct from traditional R package testing.

I'll begin by describing the application of unit, integration, and end-to-end testing in Shiny apps. Then we'll move into the role of testing in development and highlight the need for code organization when designing your testing suite.

The focus then shifts to practical aspects of testing by illustrating tools like test data and fixtures. Attendees will see example tests for utility functions, modules, and tests to capture specific user interactions (and confirm the application behaves as expected).

Finally, I will demonstrate advanced topics like test coverage, what it measures, and why 100% coverage isn't necessarily a metric worth chasing.

This presentation will give R developers a toolkit of testing techniques (building a test suite, writing effective tests, and automated testing) regardless of their familiarity with Shiny.

## Workshop Topic Index

Below is an index for each topic, slide, and chapter in [Shiny App-Packages](https://mjfrigaard.github.io/shiny-app-pkgs/). The quickest way to access each branch/app is with the [`shinypak` package](https://mjfrigaard.github.io/shinypak/).

``` r
# install.packages("pak")
pak::pak("mjfrigaard/shinypak")
library(shinypak)
```

List all the apps with `list_apps()`

``` r
head(list_apps())
#>                  branch        last_updated
#> 2     01_whole-app-game 2024-01-01 14:11:32
#> 1        02.1_shiny-app 2024-01-04 13:05:58
#> 4       02.2_movies-app 2024-01-04 13:07:59
#> 5         02.3_proj-app 2024-01-04 13:08:58
#> 6      03.1_description 2024-01-04 13:10:00
#> 7            03.2_rproj 2024-01-04 13:25:06
```

Launch an app with `launch()`

``` r
launch(app = "02.3_proj-app")
```

------------------------------------------------------------------------

### Shiny Apps and R packages

::: {style="font-size: 0.85rem;"}
+--------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| #### Topic                     | #### Video/Slide/Branch                                                                                                                                                                                        | #### Book section                                                                                                                                                                                                                                                                                                                                      |
+--------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Basic Shiny Apps**           | [6:15](https://youtu.be/HApff2wBM2I?si=GZWSOIOzZZTKdYj_) / [5](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/new-shiny-app) /`02.1_shiny-app`                                                | [Shiny Apps](https://mjfrigaard.github.io/shiny-app-pkgs/shiny.html#sec-shiny-projects) covers creating a new Shiny app in Posit Workbench and the boilerplate code.                                                                                                                                                                                   |
+--------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Advanced Shiny Apps            | [8:37](https://youtu.be/HApff2wBM2I?si=x5TWf0ZIAfOo50Ko&t=517) / [7](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/shiny-project-folders) / `02.2_movies-app`, `02.3_proj-app`               | The code for our application is introduced in [Movie review data app](https://mjfrigaard.github.io/shiny-app-pkgs/shiny.html#sec-introduce-movie-review-app), and the utility function, modules, and data are covered in [Project folders](https://mjfrigaard.github.io/shiny-app-pkgs/shiny.html#sec-shiny-folders)                                   |
+--------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `Rproj` fields                 | [13:38](https://youtu.be/HApff2wBM2I?si=4BjbXJgSJon5GEg0&t=818) / [14](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/r-package-.rproj-fields) / `03.2_rproj`                                 | [R Projects](https://mjfrigaard.github.io/shiny-app-pkgs/packages.html#r-projects) discusses what's in the `.Rproj` file (and project vs. package fields).                                                                                                                                                                                             |
+--------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Transitioning to a Package** | [20:18](https://youtu.be/HApff2wBM2I?si=YFHVaFnfnI1e2ApV&t=1218) / [15](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/creating-new-app-packages) / `03.1_description`, `03.3_create-package` | [Creating app-packages](https://mjfrigaard.github.io/shiny-app-pkgs/packages.html#creating-app-packages) covers converting and creating app-packages with `usethis::create_package()`                                                                                                                                                                  |
+--------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `DESCRIPTION` fields           | [25:51](https://youtu.be/HApff2wBM2I?si=TvwLxoN2bZk7u9cX&t=1551) / [16](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/converting-shiny-apps-fields) / `03.3_create-package`                  | Storing/supplying your personal information in new packages is discussed in [DESCRIPTION](https://mjfrigaard.github.io/shiny-app-pkgs/packages.html#description-argumentshttps://mjfrigaard.github.io/shiny-app-pkgs/packages.html#description-arguments) [arguments](https://mjfrigaard.github.io/shiny-app-pkgs/packages.html#description-arguments) |
+--------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Load, document, and install    | [28:01](https://youtu.be/HApff2wBM2I?si=EeP6BLQkvM7SUBFZ&t=1681) / [18](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/development-with-devtools) / `04_devtools`                             | Building R packages means adopting new [package development habits](https://mjfrigaard.github.io/shiny-app-pkgs/development.html#package-development-habits)                                                                                                                                                                                           |
+--------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| The benefits of `document()`   | [31:26](https://youtu.be/HApff2wBM2I?si=BNCpDydbrFYW2mdA&t=1886) / [20](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/development-document) / `04_devtools`                                  | [Documentation](https://mjfrigaard.github.io/shiny-app-pkgs/development.html#sec-dev-document) covers the multiple outputs created with `devtools::document()`                                                                                                                                                                                         |
+--------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Running `check()`              | [35:14](https://youtu.be/HApff2wBM2I?si=Fvj_lqTzDCZk9JOs&t=2114) / [23](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/development-check) / `04_devtools`                                     | How often/should you run [Check?](https://mjfrigaard.github.io/shiny-app-pkgs/development.html#sec-dev-check)                                                                                                                                                                                                                                          |
+--------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::

------------------------------------------------------------------------

### R Package Contents

::: {style="font-size: 0.85rem;"}
+--------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| #### Topic                           | #### Video/Slide/Branch                                                                                                                                                                  | #### Book section                                                                                                                                 |
+--------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| **Documentation**                    | [41:39](https://youtu.be/HApff2wBM2I?si=wNeP8HdssvxmNRCE&t=2499) / [26](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/documentation-roxygen2) / `05_roxygen2`          | Learn the basics of function documentation with [`roxygen2` basics](https://mjfrigaard.github.io/shiny-app-pkgs/document.html#sec-intro-roxygen2) |
+--------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| Help files                           | [45:03](https://youtu.be/HApff2wBM2I?si=OTccwHwIBJLtw6rN&t=2704) / [27](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/documentation-roxygen2-document) / `05_roxygen2` | Preview help files while [documenting app functions](https://mjfrigaard.github.io/shiny-app-pkgs/document.html#sec-document-app-functions)        |
+--------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| **Dependencies**                     | [47:21](https://youtu.be/HApff2wBM2I?si=P_ltFgxI5J7siD17&t=2838) / [28](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/dependencies) / `06.1_pkg-exports`               | Introduction to managing [dependencies](https://mjfrigaard.github.io/shiny-app-pkgs/dependencies.html)                                            |
+--------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| Exports                              | [49:44](https://youtu.be/HApff2wBM2I?si=qiyzhXr0yGaovDrI&t=2982) / [29](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/dependencies-exports) / `06.1_pkg-exports`       | [Exports](https://mjfrigaard.github.io/shiny-app-pkgs/dependencies.html#sec-depends-exports) from your app-package                                |
+--------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| Imports                              | [53:01](https://youtu.be/HApff2wBM2I?si=kxRVEU54Oj_7eDPs&t=3181) / [30](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/dependencies-imports) / `06.2_pkg-imports`       | [Imports](https://mjfrigaard.github.io/shiny-app-pkgs/dependencies.html#sec-depends-imports) into your app-package                                |
+--------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| **Data**                             | [1:03:15](https://youtu.be/HApff2wBM2I?si=0hIM5hPQbUga4HRt&t=3795) / [33](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/data) / `07_data`                              | Storing, loading, and documenting [data](https://mjfrigaard.github.io/shiny-app-pkgs/data.html)                                                   |
+--------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| Accessing files with `system.file()` | [1:08:51](https://youtu.be/HApff2wBM2I?si=oqq851Mgt3yXokkn&t=4130) / [37](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/using-system.file) / `07_data`                 | How to use [the `inst/extdata` folder](https://mjfrigaard.github.io/shiny-app-pkgs/data.html#sec-data-inst-extdata)                               |
+--------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
:::

------------------------------------------------------------------------

### App-Package Contents

::: {style="font-size: 0.85rem;"}
+-------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| #### Topic                                | #### Video/Slide/Branch                                                                                                                                                                            | #### Book section                                                                                                                                                                                                                                                                                                                           |
+-------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Launching apps**                        | [1:21:17](https://youtu.be/HApff2wBM2I?si=dnkLLOmoweSaEX1C&t=4877) / [40](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/launching-apps) / `08_launch-app`                        | [Launch](https://mjfrigaard.github.io/shiny-app-pkgs/launch.html) covers Shiny's three functions for running apps (`shinyApp()`, `runApp()`, and `shinyAppDir()`)                                                                                                                                                                           |
+-------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Standalone app functions                  | [1:22:07](https://youtu.be/HApff2wBM2I?si=dnkLLOmoweSaEX1C&t=4877) / [41](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/launching-apps-movies_app) / `08_launch-app`             | [Standalone options](https://mjfrigaard.github.io/shiny-app-pkgs/launch.html#standalone-options) provides some methods/approaches to writing the primary function to run your application.                                                                                                                                                  |
+-------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `app.R` files                             | [1:27:07](https://youtu.be/HApff2wBM2I?si=5pga8ulVAxz6r7sa&t=5227) / [44](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/launching-apps-app.r) / `08_launch-app`                  | [`app.R` options](https://mjfrigaard.github.io/shiny-app-pkgs/launch.html#sec-launch-app-dot-r) includes packages and functions to consider including in the root `app.R` file (and how to use it non-interactively).                                                                                                                       |
+-------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **External resources**                    | [1:30:32](https://youtu.be/HApff2wBM2I?si=YG7pA-jNdOu9vz9m&t=5432) / [45](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/external-resources) / `09.1_inst-www`                    | Most Shiny apps require some [external files](https://mjfrigaard.github.io/shiny-app-pkgs/external.html#external-files)–this chapter covers how to include them.                                                                                                                                                                            |
+-------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `addResourcePath()` and `system.file()`   | [1:31:12](https://youtu.be/HApff2wBM2I?si=zhMURS7p60Hbm3uE&t=5472) / [46](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/external-files-www) / `09.1_inst-www`, `09.2_inst-bslib` | The differences between the 'source' and 'installed' package is covered in [package files](https://mjfrigaard.github.io/shiny-app-pkgs/external.html#package-files), and including alternative image files/UI arguments is discussed in [`bslib` layout](https://mjfrigaard.github.io/shiny-app-pkgs/external.html#sec-external-inst-bslib) |
+-------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 'development' vs 'production' directories | [1:43:41](https://youtu.be/HApff2wBM2I?si=atOgvJyrmHQH3u5h&t=6221) / [48](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/external-files-dev) / `09.3_inst-dev`, `09.4_inst-prod`  | This chapter also covers how to use `inst/` to store [`dev` data](https://mjfrigaard.github.io/shiny-app-pkgs/external.html#sec-external-inst-dev) and [production (`prod`)](https://mjfrigaard.github.io/shiny-app-pkgs/external.html#sec-external-inst-prod) versions of your app                                                         |
+-------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::

------------------------------------------------------------------------

### Questions from chat

1.  ***Am I planning on contrasting this package development approach with a \[Shiny\] framework?***

    1.  Discussion of the `rhino` framework: [1:48:29](https://youtu.be/HApff2wBM2I?si=YGlulttEp9Sa8R3k&t=6509)

    2.  Shiny framework comparisons website: [1:50:35](https://youtu.be/HApff2wBM2I?si=Z8qmxl5331tt0Wkc&t=6635)

        -   [Link to site](https://mjfrigaard.github.io/sfw/)

    ```{=html}
    <!-- -->
    ```
    3.  Brief discussion of the `golem` framework: [1:51:09](https://youtu.be/HApff2wBM2I?si=VlB9ldC7LD0ZFhfH&t=6669)

2.  ***Choosing one framework over another in terms of design and how to best prepare your app as it becomes more complicated or how you choose the best way to 'future proof' your app?***

    1.  My rather lengthy non-answer starts at [1:54:14](https://youtu.be/HApff2wBM2I?si=qXP5fem4AjXyiLVj&t=6854)

3.  ***The order of learning when it comes to our Shiny versus R packages (like learning before the other)***

    1.  Shameless plug for my [Shiny App-Packages book](https://mjfrigaard.github.io/shiny-app-pkgs/) starting at: [1:56:15](https://youtu.be/HApff2wBM2I?si=zizpElY84QqE6Qdb&t=6975)

### Tests

::: {style="font-size: 0.85rem;"}
+:-----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| #### Topic                               | #### Video/Slide/Branch                                                                                                                                                                      | #### Book section                                                                                                                                                                                                                             |
+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Tests**                                | [2:00:45](https://youtu.be/HApff2wBM2I?si=cnCxfbfLRCiKr1tK&t=7244) / [51](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/tests) / `11_tests-specs`                          | [Tests](https://mjfrigaard.github.io/shiny-app-pkgs/tests.html) gives an overview of the testing section (and links to additional resources)                                                                                                  |
+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Test suite                               | [2:02:15](https://youtu.be/HApff2wBM2I?si=YecOsAHvWXr0ouC0&t=7335)/ [52](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/test-suite) / `11_tests-specs`                      | [Test suite](https://mjfrigaard.github.io/shiny-app-pkgs/test_suite.html) covers how to setup your `testthat` tests, creating new tests, running tests interactively, etc.                                                                    |
+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| App specifications                       | [2:09:46](https://youtu.be/HApff2wBM2I?si=8dcAQVPTzvf21rc4&t=7786)/ [56](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/app-specifications) / `11_tests-specs`              | [Specifications](https://mjfrigaard.github.io/shiny-app-pkgs/test_specs.html) compares user specifications, features, and functional requirements (or *how to figure out what to test*)                                                       |
+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Connecting user specifications and tests | [2:11:40](https://youtu.be/HApff2wBM2I?si=vAboLu1lrW_7nxYN&t=7900) / [57](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/test-specifications) / `11_tests-specs`            | The [traceability matrix](https://mjfrigaard.github.io/shiny-app-pkgs/test_specs.html#traceability-matrix) section gives an example of a user specification *mapped* to a feature *linked* to a functional requirement *connected* to a test. |
+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `testthat` BDD functions                 | [2:18:25](https://youtu.be/HApff2wBM2I?si=O_zOzgVT6lpJhms0&t=8305) / [59](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/describe-features-background) / `11_tests-specs`   | [BDD and `testthat`](https://mjfrigaard.github.io/shiny-app-pkgs/test_specs.html#bdd-and-testthat) covers using `describe()` and `it()` with the [Gherkin syntax](https://cucumber.io/docs/gherkin/)                                          |
+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Test fixtures                            | [2:22:07](https://youtu.be/HApff2wBM2I?si=XAPAxqLeypoBnHaB&t=8527) / [61](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/test-fixtures) / `12.1_tests-fixtures`             | The [fixtures](https://mjfrigaard.github.io/shiny-app-pkgs/test_tools.html#sec-test-fixtures) section uses the same (data) example fixture, but gives more information on using them in tests.                                                |
+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Test helpers                             | [2:32:09](https://youtu.be/HApff2wBM2I?si=-5vGuHRDYCs-897Z&t=9129) / [66](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/test-helpers) / `12.2_tests-helpers`               | [Test helpers](https://mjfrigaard.github.io/shiny-app-pkgs/test_tools.html#sec-test-helpers) covers some dos and don'ts of writing test helpers (it's OK if test code doesn't 100% adhere to the DRY principle)                               |
+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Testing modules                          | [2:37:59](https://youtu.be/HApff2wBM2I?si=kJrNilYhnpxDbBkg&t=9479) / [72](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/testing-modules) / `13_tests-modules`              | [Integration tests](https://mjfrigaard.github.io/shiny-app-pkgs/test_modules.html#integration-tests) discusses testing module server functions with `testServer()`                                                                            |
+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| System tests                             | [2:48:54](https://youtu.be/HApff2wBM2I?si=6sd8N8bvKlpabLv8&t=10134) / [82](https://mjfrigaard.github.io/dev-test-shiny/slides/wrkshp.html#/system-tests-with-shinytest2) / `14_tests-system` | [System tests](https://mjfrigaard.github.io/shiny-app-pkgs/test_system.html) covers setting up `shinytest2`, recording and writing tests.                                                                                                     |
+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::

## About Me

[Martin Frigaard](https://www.martinfrigaard.io/) is a Shiny Developer and `tidyverse` instructor. Find him on [LinkedIn](https://www.linkedin.com/in/mjfrigaard/).
